### ISSUE TITLE
[Feature] Keep history of shortened urls using cookies

### ISSUE THREAD

**Issue by kauxp** [abhijeetnishal/URLShortener#106]
## Description
When a user uses this service to shorten a URL we can store the shortened URL along with the original in browser cookies so that the user does not have to ping to shorten the same URL repeatedly. 

## Changes
When the shortened URL is returned, I will save the original and shortened URL as a key-value pair in browser cookies.

## Alternatives
We can create an authentication system where we can track all the URLs shortened by the user, this will allow us to track all URLs shortened by the user, and we can also track the number of hits on that URL. This will enable us to do anything we want.

### Contributor
**Paramjeet Kaur Matharu**
I can work on this issue and implement it.

**Comment by abhijeetnishal** [comment]
Hey @kauxp, there are many disadvantages of keeping history in cookies like:
1. Cookies have size limitations, which can restrict the number of URLs that can be stored.
2. Cookies can be vulnerable to attacks, which could compromise user data.
3. Cookies may not work consistently across different browsers, devices, or platforms.

Because of these issues, we can't implement this using cookies we can use server side storage for logged in users to see there shortened URL's, for that there is an issue #98 

contribute to other issues or projects, good luck.

**Comment by Aditya2ReaLNITKKR** [comment]
@kauxp  i want to work on this issue under ggsoc' 24
